### PR TITLE
Update installation process

### LINKED ISSUE #9: Docker does not restart
I do not see the reason why docker should be restarted. Moreover, always restarted.

### Expected behavior:
Docker does not restart
### Actual Behavior:
Docker does restart

### PR DESCRIPTION
**Pull request by dzubchik**
This resolves #9 #11 and #8. I removed ntp from dependencies because of 2 reasons:

- it is not idempotent
- it is not a dependency

Also, I added verbose mode for vagrant setup. Waiting for comments, @roquie.

### CODE REVIEW

**Comment by roquie** [comment]
1) I commented #9 and I think best solution for this is a optional docker restart. By default parameter set up to false (does not restart).
2) Yes, NTP is not a true dependency, but, if you use multiple data centers, you may catch a some bug with master node. So, logs of agent will say what the server date not synchronized with master node.

Solution for point 2 may be to document this behavior or add ntp as dependency to main task.

**Comment by dzubchik** [comment]
Ok, do we need to add ntp as a dependency? I update installation process, so docker restarts in handling by kontena's post-update or post-install. Do you think it is necessary to add this as an option? 

Btw, if we add the ntp as dependency, this role will not be idempotent anymore.

**Comment by roquie** [comment]
> Ok, do we need to add ntp as a dependency?

Maybe as an option and off by default?

>  I update installation process, so docker restarts in handling by kontena's post-update or post-install.

Mmm, okay.

> Do you think it is necessary to add this as an option?

then no.

**Comment by roquie** [comment]
thanks for your help!

**Pull request merged**
